### ISSUE TITLE
Unable to load shared library 'python37' or one of its dependencies

### ISSUE THREAD

**Issue by Cliff-Foreman** [SciSharp/Keras.NET#104] opened 2020-03-18 16:30 UTC
Hi everyone, I am quite new to dotnet and Keras.NET, and I was trying to set it up on a goorm.io container. After installing the prerequisites (adding $HOME/.keras/keras.json for Tensorflow backend and pip install numpy), and then adding Keras.NET, I tried to run the XOR sample code, but ran into an error. 

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'python37' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython37: cannot open shared object file: No such file or directory
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Numpy.np.InstallAndImport(Boolean force)
   at Numpy.np.<>c.<.cctor>b__599_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Numpy.np.get_self()
   at Numpy.np.get_float32()
   at Numpy.DtypeExtensions.GetDtype(Object obj)
   at Numpy.np.array[T](T[,] object, Dtype dtype, Nullable`1 copy, String order, Nullable`1 subok, Nullable`1 ndmin)
   at Proj.Program.Main(String[] args) in /workspace/XOR/Proj/Program.cs:line 14

I do not know how to share with the python37 directory. If someone could direct me in the right direction, it would be much appreciated. By the way, I am using Linux if that helps.

Thanks

**Comment by dsimeonov140** [comment] 2020-03-21 10:23
Try to add this at the beginning of the program (replace "YOUR_PYTHON_DIRECTORY" with the directory where the python is installed):

```
string path = @"YOUR_PYTHON_DIRECTORY;" + Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.Machine);
Environment.SetEnvironmentVariable("PATH", path, EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("PYTHONHOME", @"YOUR_PYTHON_DIRECTORY", EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("PYTHONPATH ", @"YOUR_PYTHON_DIRECTORY", EnvironmentVariableTarget.Process);
```

**Comment by deepakkumar1984** [comment] 2020-05-01 01:32
Hope the issue is fixed with solution provided by @dsimeonov140 and krishnanpc

**Closed as completed by deepakkumar1984** 2020-05-01 01:32 UTC
